version: "3.8"
services: 
  db:
    image: postgres:13
    ports:
      - 32700:5432
    volumes:
      - ./project:/usr/src/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employment_exchange